# Generated by Django 4.2.1 on 2023-05-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='ФИО')),
                ('gender', models.CharField(max_length=120, verbose_name='Жынысы')),
                ('birth_day', models.CharField(max_length=120, verbose_name='Тууган күнү')),
                ('class_of_year', models.CharField(max_length=120, verbose_name='Бүтүргөн классы')),
                ('region', models.TextField(verbose_name='Жашаган жери')),
                ('phone_number_student', models.CharField(max_length=120, verbose_name='Окуучунун жашаган жери')),
                ('name_of_dum_mum', models.TextField(verbose_name='Ата-энесини аты-жөнү')),
                ('phone_of_dum_mum', models.CharField(max_length=120, verbose_name='Ата-энесинин телефону')),
                ('name_guardian', models.CharField(max_length=120, verbose_name='Жоопту киши')),
                ('phone_guardian', models.CharField(max_length=120, verbose_name='Жоопту кишинин номери')),
                ('whatsapp', models.CharField(max_length=120, verbose_name='Ватсап номери')),
                ('interesting_lesson', models.TextField(verbose_name='Кызыккан сабагы')),
                ('success', models.CharField(max_length=120, verbose_name='Ийгиликтери')),
                ('hobbies', models.CharField(max_length=120, verbose_name='Өнөрлөрү(Жөндөмдүүлүктөрү)')),
            ],
        ),
    ]
