# Generated by Django 4.2.1 on 2023-05-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name_of_dum_mum',
            new_name='name_of_dud_mum',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phone_of_dum_mum',
            new_name='phone_of_dud_mum',
        ),
        migrations.AlterField(
            model_name='student',
            name='hobbies',
            field=models.TextField(max_length=120, verbose_name='Өнөрлөрү(Жөндөмдүүлүктөрү)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number_student',
            field=models.CharField(max_length=120, verbose_name='Окуучунун телефон номери'),
        ),
        migrations.AlterField(
            model_name='student',
            name='success',
            field=models.TextField(max_length=120, verbose_name='Ийгиликтери'),
        ),
    ]
